version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html
  - source: /about.html
    destination: /var/www/html
  - source: /service.html
    destination: /var/www/html
  - source: /contact.html
    destination: /var/www/html
  - source: /style.css
    destination: /var/www/html
hoos:
  BeforeInstall:
    - location: scripts/dep.sh
      timeout: 240
      runas: root
